INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'An epic trilogy that blends action, space exploration, and an engaging narrative, where your choices shape the future of the galaxy. Prepare to interact with memorable characters and make decisions that will affect the fate of the universe.', 'Mass Effect Trilogy is an action RPG with a strong focus on narrative and impactful choices. The player takes on the role of Commander Shepard, leader of the Normandy spaceship, as they explore the vast universe, face alien threats, form alliances, and make decisions that can save or destroy entire civilizations. With impressive graphics and an engaging story, the series is considered one of the best in the genre, offering hours of gameplay and a deep sense of immersion.')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'In a detailed and vibrant open world, Red Dead Redemption 2 puts you in the role of Arthur Morgan, a member of an outlaw gang. Fight for survival as the Old West fades around you.', 'Red Dead Redemption 2 is an action-adventure open-world game set at the end of the 19th century, where you play as Arthur Morgan, an outlaw and member of the Van der Linde gang. The game offers a richly detailed environment, allowing the player to hunt, fish, rob, and even interact with NPCs in a realistic manner. The deep story and the moral dilemmas Arthur faces make the journey emotionally engaging, with a strong emphasis on immersing the player in the Old West as the gang fights for survival amidst the changes of the era.')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Geralt of Rivia, the monster hunter, embarks on a dangerous quest to find his adopted daughter in a world filled with magic, monsters, and tough choices. One of the most epic adventures of all time.', 'The Witcher 3: Wild Hunt is an action RPG with a rich narrative where the player takes on the role of Geralt of Rivia, a monster hunter known as a Witcher. The game features a vast open world where the choices the player makes influence the story and the fate of its characters. Geralt faces a variety of monsters, while also dealing with a complex political and mythological story. The gameplay involves exploration, combat, and a web of characters and quests. Considered one of the greatest games of all time, The Witcher 3 offers a deep and engaging experience that captivates players in every aspect of its gameplay.')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Sekiro is an action-adventure game with challenging combat, where you play as a samurai seeking revenge. Get ready to face relentless enemies in a feudal Japan overrun by monsters and demons.', 'Sekiro: Shadows Die Twice is an action-adventure game that blends strategic combat with exploration. Set in feudal Japan, the player takes on the role of a samurai named Wolf, seeking revenge against those who wronged him. The game is known for its challenging combat, where every move matters, and its progression system allows the player to learn new skills while exploring a dangerous world full of secrets. The story revolves around themes of honor, revenge, and redemption, with gameplay that challenges even the most experienced players.')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Ghost of Tsushima blends action with samurai culture. The game follows Jin Sakai as he tries to defend his homeland from Mongol invasions, defying traditions to become the "Ghost" of Tsushima.', 'Ghost of Tsushima is an action-adventure game set in feudal Japan, where the player takes on the role of Jin Sakai, a samurai trying to protect his homeland, Tsushima Island, from the Mongol invasion. The gameplay blends sword combat, stealth, and exploration. Jin is forced to break the samurai code to become the "Ghost", fighting in unconventional ways. The game is visually stunning, with an open world filled with beauty and a story that explores honor, sacrifice, and resistance against oppressive forces.')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Super Mario World is a platformer that defines the genre. Follow Mario and Luigi as they try to rescue Princess Toadstool in a world full of enemies, jumps, and challenges.', 'Super Mario World is a platform game developed by Nintendo and released for the Super Nintendo Entertainment System (SNES). The game follows Mario and his brother Luigi as they try to rescue Princess Toadstool from the villain Bowser. With colorful graphics and smooth gameplay, the game introduces new features like Yoshi, a dinosaur companion to Mario. The open world allows exploration of various levels and challenging enemies, making Super Mario World one of the most beloved games of all time.')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'In Hollow Knight, you explore the vast underground kingdom of Hallownest, facing mysterious creatures while uncovering the secrets of this dark and fascinating world.', 'Hollow Knight is a platform action game in the "metroidvania" style that puts the player in control of a knight on a journey to explore the vast, dark, underground kingdom of Hallownest. The game features challenging combat, exploration, and a narrative revealed throughout gameplay. With beautifully hand-drawn graphics and an engaging soundtrack, Hollow Knight is a game that rewards patience and curiosity, challenging players to overcome formidable enemies and uncover hidden secrets.')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Ori and the Blind Forest is an emotional journey about overcoming obstacles and friendship, where Ori, a small creature, must save his home forest with special abilities and exciting challenges.', 'Ori and the Blind Forest is a platform game with a strong narrative focus, where the player controls Ori, a small creature trying to save their home, the forest of Nibel, from an impending disaster. The game blends exploration, platforming, and puzzles with an emotionally engaging story that touches on themes of friendship, sacrifice, and hope. With beautifully hand-drawn art and an acclaimed soundtrack, Ori and the Blind Forest is an unforgettable experience for any gamer.')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Cuphead is a platform game inspired by 1930s cartoons, with challenging combat and a unique visual style that captivates with nostalgia and difficulty.', 'Cuphead is a platform action game with a unique aesthetic inspired by 1930s cartoons. The game challenges players with incredibly difficult boss battles, where learning attack patterns and improving skills is key to victory. The gameplay is fast-paced and frantic, with precise controls and a high level of difficulty. Each stage offers charming visuals and a jazz-inspired soundtrack, making Cuphead both a nostalgic and challenging experience.')
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Sonic CD is one of the greatest classics of the franchise, where Sonic travels through time to save the future and stop Dr. Robotnik from conquering the world.', 'Sonic CD is a classic platform game for the Sega CD. The game features Sonic on an adventure that involves time travel to save the future from the domination of the villain Dr. Robotnik. With new characters and settings, Sonic CD introduces the mechanic of time travel, where the player can change the future of different locations by collecting items and defeating enemies. With an iconic soundtrack and colorful graphics, Sonic CD is one of the most beloved entries in the franchise.')


INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);